# experiment params
NUM_SEEDS: 1
SEED: 0

# if  hyperparameters tuning
HYP_TUNE: False

# wandb params
WANDB_MODE: "online"  # set to online to activate wandb
ENTITY: "flair"
PROJECT: "nate_jaxued"
alg:
  WANDB_LOG_ALL_SEEDS: False # will log all the vmapped seeds separetely

# where to save the params (if None, will not save)
SAVE_PATH: "./models"
